services:
#  api:
#    container_name: electit-api
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - '8080:8080'
#    env_file:
#      - .env
#    depends_on:
#      neo4j:
#        condition: service_started

  neo4j:
    container_name: neo4j-db
    image: 'neo4j:latest'
    environment:
      - 'NEO4J_AUTH=neo4j/P@ssw0rd'
    ports:
      - '7687:7687'
      - '7474:7474'
    volumes:
      - neo4j-data:/data

volumes:
  neo4j-data:
    driver: local
