name: electit_frontend
description: "eLectIT Frontend"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  graphql: ^5.1.3
  flutter_bloc: ^8.1.6
  flutter_form_bloc: ^0.31.0
  auto_route: ^9.2.2
  hive: ^2.2.3
  path_provider: ^2.1.5
  shared_preferences: ^2.3.4
  jwt_decoder: ^2.0.1
  get_it: ^8.0.3
  injectable: ^2.5.0
  fpdart: ^1.1.1
  fl_chart: ^0.69.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  graphql_codegen: ^1.1.1
  build_runner: ^2.4.13
  injectable_generator: ^2.4.2
  auto_route_generator: ^9.0.0

flutter:
  uses-material-design: true
